# DO NOT EDIT THIS FILE!
#
# Python module fr.upem generated by omniidl

import omniORB
omniORB.updateModule("fr.upem")

# ** 1. Stub files contributing to this module
import Robot_idl

# ** 2. Sub-modules
import robot

# ** 3. End
