# DO NOT EDIT THIS FILE!
#
# Python module fr__POA generated by omniidl

import omniORB
omniORB.updateModule("fr__POA")

# ** 1. Stub files contributing to this module
import Robot_idl

# ** 2. Sub-modules
import upem

# ** 3. End
