# DO NOT EDIT THIS FILE!
#
# Python module fr generated by omniidl

import omniORB
omniORB.updateModule("fr")

# ** 1. Stub files contributing to this module
import Robot_idl

# ** 2. Sub-modules
import upem

# ** 3. End
