# DO NOT EDIT THIS FILE!
#
# Python module fr__POA.upem.robot generated by omniidl

import omniORB
omniORB.updateModule("fr__POA.upem.robot")

# ** 1. Stub files contributing to this module
import Robot_idl

# ** 2. Sub-modules

# ** 3. End
